# Site settings
title: 巴蛮子的笔记
email: bamanzi@gmail.com
description: "主博客在博客园 <http://bamanzi.cnblogs.com> . 这里一方面是博客文章的备份，另一方面也存放一些wiki性质的页面以方便快速查找常用信息"
baseurl: ""
url: "http://bamanzi.cnblogs.com"
twitter_username: bamanzi
github_username:  bamanzi

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
    input: GFM
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "wiki"
      type: "page"
    values:
      layout: "page" # overrides previous default layout
      author: "Mr. Hyde"

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
